### ISSUE TITLE
not compatible with the latest version of react native

### ISSUE THREAD

**Issue by sicson** [tokict/react-native-comments#17]
As I would like to make bulletin board by react native 0.63.2, I’ve found that react-native-comments would be suitable for my project, version is 0.55.4.

Due to the difference between react native, I could not use your project.
not only coding styles are different, but it cannot be compiled on these examples with the latest version.

So would it be possible to make a updated version to be compatible with the latest version of react native - which is 0.63

Thanks

**Comment by tokict** [comment]
I have updated the test app to work with RN 0.63.4.
The lib itself worked properly with all react versions, the issue was that the testApp did not because of the react-native-vector-icons package which you must install manually and for your app.

Some packages are updated to latest versions. Please try to run the testApp in v.1.1.9 and let me know how it goes

**Comment by sicson** [comment]
Thank you for updating in your testApp.

I didn't know that I can check the npmjs not in github.
Anyway I'll try to use your testApp in 1.1.9 and let you know how it goes.
