### ISSUE TITLE
Performance is lacking

### ISSUE THREAD

**Issue by amirbhz86** [tokict/react-native-comments#19]
I'm using this library
but It takes some time to load the offline comments
also displaying replied comments and sending messages is slow
what should I do for improving the performance ??

**Comment by tokict** [comment]
Is it caused by data fetching or rendering?
From my experience, serializing / deserializing json from local storage can be very slow, depending on the size.
Try keeping the comments directly in memory and see if the problem persists.
However, sending should be instant and the fact that it's not tells me you have an underlying problem in your data manipulation
