### ISSUE TITLE
The entered text from the TextInput is not cleared after pressing  Submit button

### ISSUE THREAD

**Issue by fighterinthewind** [tokict/react-native-comments#3]
After entering some text in the TextInput field and pressing the Submit button (on the right side) the entered text is not cleared automatically, could you fix this?
Thanks!

"react": "16.3.1",
"react-native": "0.55.2"
 iOS version: 11.3

**Comment by tokict** [comment]
It seems this is a bug with updating native props in newest react-native. I can't do anything about it as I have no way of updating it in that version. I suggest you revert to older RN. I have confirmed that at least 0.51 works. Probably up until 0.54 but I cant guarantee as I don't know when the bug was introduced

https://github.com/facebook/react-native/issues/18272
